import type { AdSlot, Site, Submission } from './types'

/**
 * Fallback content used when Supabase is not configured (fresh clone, preview
 * builds, local `next dev` without a .env). Mirrors supabase/schema.sql seeds
 * so the directory looks the same before and after you connect a database.
 */

const day = 86_400_000
const daysAgo = (n: number) => new Date(Date.now() - n * day).toISOString()
/** Launch dates are relative so the demo never reads as a stale snapshot. */
const launchedDaysAgo = (n: number) => new Date(Date.now() - n * day).toISOString().slice(0, 10)

export const DEMO_SITES: Site[] = [
  {
    id: 'demo-1',
    name: 'Outbid.lol',
    url: 'https://outbid.lol',
    description: 'Pay more than the person above you and take the top slot.',
    model_type: 'bid',
    revenue: 184320,
    prev_revenue: 171400,
    launched_at: launchedDaysAgo(590),
    is_verified: true,
    source_link: 'https://outbid.lol',
    created_at: daysAgo(210),
  },
  {
    id: 'demo-2',
    name: 'OneMillionPixels',
    url: 'https://example.com/pixels',
    description: 'A grid of pixels sold once, at a dollar a piece.',
    model_type: 'pixel',
    revenue: 102400,
    prev_revenue: 99800,
    launched_at: launchedDaysAgo(470),
    is_verified: true,
    source_link: null,
    created_at: daysAgo(190),
  },
  {
    id: 'demo-3',
    name: 'ShipBoard',
    url: 'https://example.com/ship',
    description: 'A leaderboard of makers ranked by streak length.',
    model_type: 'leaderboard',
    revenue: 61250,
    prev_revenue: 52300,
    launched_at: launchedDaysAgo(320),
    is_verified: true,
    source_link: null,
    created_at: daysAgo(150),
  },
  {
    id: 'demo-4',
    name: 'SponsorRow',
    url: 'https://example.com/row',
    description: 'One sponsor per row, one row per week.',
    model_type: 'sponsor',
    revenue: 44800,
    prev_revenue: 44100,
    launched_at: launchedDaysAgo(240),
    is_verified: false,
    source_link: null,
    created_at: daysAgo(120),
  },
  {
    id: 'demo-5',
    name: 'HighestBidder',
    url: 'https://example.com/hb',
    description: 'A single button that belongs to whoever paid the most.',
    model_type: 'bid',
    revenue: 31900,
    prev_revenue: 24600,
    launched_at: launchedDaysAgo(180),
    is_verified: true,
    source_link: null,
    created_at: daysAgo(74),
  },
  {
    id: 'demo-6',
    name: 'PixelWall',
    url: 'https://example.com/wall',
    description: 'Ten thousand pixels, resold every quarter.',
    model_type: 'pixel',
    revenue: 18750,
    prev_revenue: 18400,
    launched_at: launchedDaysAgo(130),
    is_verified: false,
    source_link: null,
    created_at: daysAgo(52),
  },
  {
    id: 'demo-7',
    name: 'StreakRank',
    url: 'https://example.com/streak',
    description: 'Daily leaderboard for build-in-public streaks.',
    model_type: 'leaderboard',
    revenue: 12300,
    prev_revenue: 8900,
    launched_at: launchedDaysAgo(96),
    is_verified: true,
    source_link: null,
    created_at: daysAgo(30),
  },
  {
    id: 'demo-8',
    name: 'SoloSponsor',
    url: 'https://example.com/solo',
    description: 'Exactly one sponsor slot, auctioned monthly.',
    model_type: 'sponsor',
    revenue: 9400,
    prev_revenue: 6100,
    launched_at: launchedDaysAgo(64),
    is_verified: false,
    source_link: null,
    created_at: daysAgo(12),
  },
  {
    id: 'demo-9',
    name: 'BidTheHeadline',
    url: 'https://example.com/bth',
    description: 'The headline of the page is for sale, always.',
    model_type: 'bid',
    revenue: 5200,
    prev_revenue: 3050,
    launched_at: launchedDaysAgo(38),
    is_verified: false,
    source_link: null,
    created_at: daysAgo(5),
  },
  {
    id: 'demo-10',
    name: 'DotGrid',
    url: 'https://example.com/dot',
    description: 'A dot costs a dollar. Buying two makes a line.',
    model_type: 'pixel',
    revenue: 2100,
    prev_revenue: 850,
    launched_at: launchedDaysAgo(17),
    is_verified: false,
    source_link: null,
    created_at: daysAgo(1),
  },
]

export const DEMO_AD_SLOTS: AdSlot[] = [
  {
    id: 'slot-1',
    position: 1,
    company_name: 'Outbid.lol',
    url: 'https://outbid.lol',
    description: 'The original pay-to-rank leaderboard.',
    is_filled: true,
    stripe_subscription_id: null,
  },
  {
    id: 'slot-2',
    position: 2,
    company_name: 'PixelVault',
    url: 'https://example.com',
    description: 'Buy a pixel, own it forever.',
    is_filled: true,
    stripe_subscription_id: null,
  },
  {
    id: 'slot-3',
    position: 3,
    company_name: 'IndieBoard',
    url: 'https://example.com',
    description: 'Where indie hackers ship in public.',
    is_filled: true,
    stripe_subscription_id: null,
  },
  { id: 'slot-4', position: 4, company_name: null, url: null, description: null, is_filled: false, stripe_subscription_id: null },
  { id: 'slot-5', position: 5, company_name: null, url: null, description: null, is_filled: false, stripe_subscription_id: null },
  { id: 'slot-6', position: 6, company_name: null, url: null, description: null, is_filled: false, stripe_subscription_id: null },
]

export const DEMO_SUBMISSIONS: Submission[] = [
  {
    id: 'sub-1',
    url: 'https://example.com/dot',
    name: 'DotGrid',
    description: 'A dot costs a dollar.',
    model_type: 'pixel',
    revenue: 2100,
    source_link: null,
    submitted_at: daysAgo(1),
  },
  {
    id: 'sub-2',
    url: 'https://example.com/bth',
    name: 'BidTheHeadline',
    description: 'The headline is for sale.',
    model_type: 'bid',
    revenue: 5200,
    source_link: null,
    submitted_at: daysAgo(5),
  },
  {
    id: 'sub-3',
    url: 'https://example.com/solo',
    name: 'SoloSponsor',
    description: 'One sponsor slot, auctioned monthly.',
    model_type: 'sponsor',
    revenue: 9400,
    source_link: null,
    submitted_at: daysAgo(12),
  },
  {
    id: 'sub-4',
    url: 'https://example.com/streak',
    name: 'StreakRank',
    description: 'Streak leaderboard for makers.',
    model_type: 'leaderboard',
    revenue: 12300,
    source_link: null,
    submitted_at: daysAgo(30),
  },
  {
    id: 'sub-5',
    url: 'https://example.com/hb',
    name: 'HighestBidder',
    description: 'One button, highest bidder wins.',
    model_type: 'bid',
    revenue: 31900,
    source_link: null,
    submitted_at: daysAgo(74),
  },
]
