import { NextResponse } from 'next/server'
import { getSupabaseAdmin } from '@/lib/supabase/admin'
import { getSupabase } from '@/lib/supabase/client'

export const runtime = 'nodejs'
// Must stay dynamic: with `revalidate` and no request input, Next prerenders a
// route at build time and freezes the answer.
export const dynamic = 'force-dynamic'

const NO_STORE = { 'cache-control': 'no-store' }

/**
 * How long a session counts as live after its last heartbeat.
 *
 * Heartbeats arrive every 30 seconds, so two minutes tolerates three missed
 * beats before a visitor drops off — long enough to survive a slow network,
 * short enough that a closed tab disappears quickly.
 */
const STALE_MINUTES = 2

/** Session ids are generated by the browser, so bound what we will store. */
const VALID_ID = /^[A-Za-z0-9_-]{8,64}$/

function cutoff(): string {
  return new Date(Date.now() - STALE_MINUTES * 60_000).toISOString()
}

/** Live count. Stale rows are excluded whether or not they have been deleted. */
export async function GET() {
  const admin = getSupabaseAdmin()

  if (admin) {
    const { count, error } = await admin
      .from('active_visitors')
      .select('id', { count: 'exact', head: true })
      .gt('last_seen', cutoff())

    if (!error) return NextResponse.json({ live: count ?? 0 }, { headers: NO_STORE })
    console.error('[visitor] count failed:', error.message)
  }

  // No service key: fall back to the security-definer function, which is the
  // only way the anon key can see this table at all.
  const supabase = getSupabase()
  if (!supabase) return NextResponse.json({ live: 0 }, { headers: NO_STORE })

  const { data, error } = await supabase.rpc('count_visitors')
  if (error) {
    console.error('[visitor] count_visitors failed:', error.message)
    return NextResponse.json({ live: 0 }, { headers: NO_STORE })
  }

  return NextResponse.json({ live: Number(data ?? 0) }, { headers: NO_STORE })
}

/**
 * Heartbeat: sweep the stale rows, record this session, count what is left.
 *
 * The sweep runs here rather than only inside the database function so the
 * window can be changed by a deploy alone — a Postgres function only changes
 * when someone runs a migration.
 *
 * A failure is never worth surfacing: the badge hides below two, so an error
 * simply means it does not appear.
 */
export async function POST(request: Request) {
  let id: string
  try {
    const body = (await request.json()) as { id?: unknown }
    id = String(body.id ?? '')
  } catch {
    return NextResponse.json({ error: 'Invalid JSON body.' }, { status: 400 })
  }

  if (!VALID_ID.test(id)) {
    return NextResponse.json({ error: 'Invalid session id.' }, { status: 400 })
  }

  const admin = getSupabaseAdmin()

  if (admin) {
    const stale = cutoff()

    // Delete first, so a visitor who has been away longer than the window is
    // gone before their own row is written fresh.
    const { error: sweepError } = await admin
      .from('active_visitors')
      .delete()
      .lt('last_seen', stale)

    if (sweepError) console.error('[visitor] sweep failed:', sweepError.message)

    const { error: upsertError } = await admin
      .from('active_visitors')
      .upsert({ id, last_seen: new Date().toISOString() }, { onConflict: 'id' })

    if (upsertError) {
      console.error('[visitor] upsert failed:', upsertError.message)
      return NextResponse.json({ live: 0 }, { headers: NO_STORE })
    }

    const { count, error: countError } = await admin
      .from('active_visitors')
      .select('id', { count: 'exact', head: true })
      .gt('last_seen', stale)

    if (countError) {
      console.error('[visitor] count failed:', countError.message)
      return NextResponse.json({ live: 0 }, { headers: NO_STORE })
    }

    return NextResponse.json({ live: count ?? 0 }, { headers: NO_STORE })
  }

  // No service key: the database function does the same three steps in one
  // round trip, and is the only path the anon key can take.
  const supabase = getSupabase()
  if (!supabase) return NextResponse.json({ live: 0 }, { headers: NO_STORE })

  const { data, error } = await supabase.rpc('touch_visitor', { visitor_id: id })
  if (error) {
    console.error('[visitor] touch_visitor failed:', error.message)
    return NextResponse.json({ live: 0 }, { headers: NO_STORE })
  }

  return NextResponse.json({ live: Number(data ?? 0) }, { headers: NO_STORE })
}
