import { NextResponse } from 'next/server'
import { getSupabaseAdmin } from '@/lib/supabase/admin'
import { getSupabase } from '@/lib/supabase/client'

export const runtime = 'nodejs'
// Must stay dynamic: with `revalidate` and no request input, Next prerenders a
// route at build time and freezes the answer.
export const dynamic = 'force-dynamic'

const NO_STORE = { 'cache-control': 'no-store' }

/** Session ids are generated by the browser, so bound what we will store. */
const VALID_ID = /^[A-Za-z0-9_-]{8,64}$/

/** Current live count, for the first render and the polling reads. */
export async function GET() {
  const supabase = getSupabase()
  if (!supabase) return NextResponse.json({ live: 0 }, { headers: NO_STORE })

  const { data, error } = await supabase.rpc('count_visitors')

  if (error) {
    console.error('[visitor] count failed:', error.message)
    return NextResponse.json({ live: 0 }, { headers: NO_STORE })
  }

  return NextResponse.json({ live: Number(data ?? 0) }, { headers: NO_STORE })
}

/**
 * Heartbeat. Records this session, sweeps anyone quiet for five minutes, and
 * returns how many remain.
 *
 * All three happen inside `touch_visitor`, so it is one round trip and the
 * sweep needs no cron. A failure is never worth surfacing — the badge simply
 * does not appear — so every error path returns 200 with a zero.
 */
export async function POST(request: Request) {
  let id: string
  try {
    const body = (await request.json()) as { id?: unknown }
    id = String(body.id ?? '')
  } catch {
    return NextResponse.json({ error: 'Invalid JSON body.' }, { status: 400 })
  }

  if (!VALID_ID.test(id)) {
    return NextResponse.json({ error: 'Invalid session id.' }, { status: 400 })
  }

  const supabase = getSupabaseAdmin() ?? getSupabase()
  if (!supabase) return NextResponse.json({ live: 0 }, { headers: NO_STORE })

  const { data, error } = await supabase.rpc('touch_visitor', { visitor_id: id })

  if (error) {
    console.error('[visitor] heartbeat failed:', error.message)
    return NextResponse.json({ live: 0 }, { headers: NO_STORE })
  }

  return NextResponse.json({ live: Number(data ?? 0) }, { headers: NO_STORE })
}
